# Generated by Django 5.0.6 on 2024-05-30 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentapp', '0001_initial'),
        ('zuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='zuser.player'),
        ),
    ]
