# Generated by Django 5.0.6 on 2024-06-07 00:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0001_initial'),
        ('zuser', '0004_agent_aspin_margin'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinticket',
            name='choice_type',
            field=models.CharField(default=True, max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SpinAnalytica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_type', models.CharField(choices=[('promo4', 'Promo 4'), ('mohio', 'Mohio'), ('promo', 'Promo'), ('promo2', 'Promo 2'), ('promo3', 'Promo 3'), ('promo5', 'Promo 5'), ('promo6', 'Promo 6'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('mohio2', 'Mohio 2')], default='default', max_length=20)),
                ('choosen_strategy', models.CharField(blank=True, max_length=20, null=True)),
                ('total_won', models.IntegerField(default=0)),
                ('loss_percent', models.IntegerField(default=0)),
                ('total_tickets', models.IntegerField(default=0)),
                ('total_stake', models.IntegerField(default=0)),
                ('special_prize', models.BooleanField(default=False)),
                ('total_gain', models.IntegerField(default=0)),
                ('expected_gain', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cancelled_tickets', models.IntegerField(default=0)),
                ('gain_percentage', models.IntegerField(default=0)),
                ('total_special_prize', models.IntegerField(default=0)),
                ('prize_made', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spinanalytic', to='zuser.agent')),
                ('gameId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spinanalytic_set', to='spin.spin')),
            ],
        ),
    ]
