# Generated by Django 5.0.6 on 2024-07-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0003_spinticket_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spinanalytica',
            old_name='odd_type',
            new_name='spin_odd_type',
        ),
    ]
