# Generated by Django 5.0.6 on 2024-07-12 18:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spin', '0005_rename_choice_type_spinticket_choice_val_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spinticket',
            name='win_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='spinticket',
            name='kind',
            field=models.CharField(max_length=20),
        ),
    ]
