# Generated by Django 5.0.6 on 2024-06-07 00:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zuser', '0003_agent_spin_give_away_amount_agent_spin_odd_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='aspin_margin',
            field=models.IntegerField(blank=True, default=10, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
        ),
    ]
