# Generated by Django 5.0.6 on 2024-07-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zuser', '0004_agent_aspin_margin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_margin',
            new_name='keno_margin',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='odd_type',
            new_name='keno_odd_type',
        ),
        migrations.RenameField(
            model_name='agent',
            old_name='aspin_margin',
            new_name='spin_margin',
        ),
        migrations.RenameField(
            model_name='gamehistory',
            old_name='agent_margin',
            new_name='keno_margin',
        ),
    ]
