# Generated by Django 5.0.6 on 2024-05-30 19:48

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_num', models.IntegerField(db_index=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('game_type', models.CharField(db_index=True, default='keno', max_length=15)),
                ('odd_type', models.CharField(choices=[('B', 'B'), ('A', 'A')], default='A', max_length=20)),
                ('result_gen_try', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GameAnalytica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_type', models.CharField(choices=[('B', 'B'), ('A', 'A')], default='B', max_length=20)),
                ('choosen_strategy', models.CharField(blank=True, max_length=20, null=True)),
                ('total_won', models.IntegerField(default=0)),
                ('loss_percent', models.IntegerField(default=0)),
                ('total_tickets', models.IntegerField(default=0)),
                ('total_stake', models.IntegerField(default=0)),
                ('special_prize', models.BooleanField(default=False)),
                ('total_gain', models.IntegerField(default=0)),
                ('expected_gain', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cancelled_tickets', models.IntegerField(default=0)),
                ('gain_percentage', models.IntegerField(default=0)),
                ('total_special_prize', models.IntegerField(default=0)),
                ('prize_made', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
                ('order', models.IntegerField(null=True)),
                ('resultId', models.IntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_num', models.IntegerField(db_index=True, null=True)),
                ('status', models.CharField(default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(db_index=True)),
                ('updated_at', models.DateTimeField(db_index=True)),
                ('game_type', models.CharField(db_index=True, default='keno', max_length=15)),
                ('odd_type', models.CharField(choices=[('B', 'B'), ('A', 'A')], default='A', max_length=20)),
                ('result_gen_try', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MobileGameAnalytica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odd_type', models.CharField(choices=[('B', 'B'), ('A', 'A')], default='B', max_length=20)),
                ('choosen_strategy', models.CharField(blank=True, max_length=20, null=True)),
                ('total_won', models.IntegerField(default=0)),
                ('loss_percent', models.IntegerField(default=0)),
                ('total_tickets', models.IntegerField(default=0)),
                ('total_stake', models.IntegerField(default=0)),
                ('special_prize', models.BooleanField(default=False)),
                ('total_gain', models.IntegerField(default=0)),
                ('expected_gain', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cancelled_tickets', models.IntegerField(default=0)),
                ('gain_percentage', models.IntegerField(default=0)),
                ('total_special_prize', models.IntegerField(default=0)),
                ('prize_made', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MobileGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(null=True)),
                ('order', models.IntegerField(null=True)),
                ('resultId', models.IntegerField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MobileTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_list', models.TextField(db_index=True, default='[]')),
                ('stake', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('won_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('redeemed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('unique_identifier', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ticket_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('multiple_stake', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_list', models.TextField(db_index=True, default='[]')),
                ('stake', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('won_amount', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('redeemed', models.BooleanField(default=False)),
                ('cancelled', models.BooleanField(default=False)),
                ('unique_identifier', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('ticket_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('multiple_stake', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)])),
                ('_odd', models.IntegerField(default=0)),
            ],
        ),
    ]
