# Generated by Django 5.0.6 on 2024-05-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keno', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='_done',
            field=models.BooleanField(default=False),
        ),
    ]
