# Generated by Django 5.0.6 on 2024-05-30 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keno', '0003_game__done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobilegameresult',
            name='_user',
        ),
    ]
