# Generated by Django 5.0.6 on 2024-05-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keno', '0004_remove_mobilegameresult__user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='odd_type',
            field=models.CharField(choices=[('mohio', 'Mohio'), ('promo', 'Promo'), ('promo2', 'Promo 2'), ('promo3', 'Promo 3'), ('promo4', 'Promo 4'), ('promo5', 'Promo 5'), ('promo6', 'Promo 6'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('mohio2', 'Mohio 2')], default='promo4', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameanalytica',
            name='odd_type',
            field=models.CharField(choices=[('mohio', 'Mohio'), ('promo', 'Promo'), ('promo2', 'Promo 2'), ('promo3', 'Promo 3'), ('promo4', 'Promo 4'), ('promo5', 'Promo 5'), ('promo6', 'Promo 6'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('mohio2', 'Mohio 2')], default='promo4', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilegame',
            name='odd_type',
            field=models.CharField(choices=[('mohio', 'Mohio'), ('promo', 'Promo'), ('promo2', 'Promo 2'), ('promo3', 'Promo 3'), ('promo4', 'Promo 4'), ('promo5', 'Promo 5'), ('promo6', 'Promo 6'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('mohio2', 'Mohio 2')], default='promo4', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilegameanalytica',
            name='odd_type',
            field=models.CharField(choices=[('mohio', 'Mohio'), ('promo', 'Promo'), ('promo2', 'Promo 2'), ('promo3', 'Promo 3'), ('promo4', 'Promo 4'), ('promo5', 'Promo 5'), ('promo6', 'Promo 6'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('mohio2', 'Mohio 2')], default='promo4', max_length=20),
        ),
    ]
