# Generated by Django 5.0.6 on 2024-06-04 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keno', '0005_alter_game_odd_type_alter_gameanalytica_odd_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='odd_type',
            field=models.CharField(choices=[('promo4', 'Promo 4'), ('mohio', 'Mohio'), ('promo', 'Promo'), ('promo2', 'Promo 2'), ('promo3', 'Promo 3'), ('promo5', 'Promo 5'), ('promo6', 'Promo 6'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('mohio2', 'Mohio 2')], default='promo4', max_length=20),
        ),
        migrations.AlterField(
            model_name='gameanalytica',
            name='odd_type',
            field=models.CharField(choices=[('promo4', 'Promo 4'), ('mohio', 'Mohio'), ('promo', 'Promo'), ('promo2', 'Promo 2'), ('promo3', 'Promo 3'), ('promo5', 'Promo 5'), ('promo6', 'Promo 6'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('mohio2', 'Mohio 2')], default='promo4', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilegame',
            name='odd_type',
            field=models.CharField(choices=[('promo4', 'Promo 4'), ('mohio', 'Mohio'), ('promo', 'Promo'), ('promo2', 'Promo 2'), ('promo3', 'Promo 3'), ('promo5', 'Promo 5'), ('promo6', 'Promo 6'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('mohio2', 'Mohio 2')], default='promo4', max_length=20),
        ),
        migrations.AlterField(
            model_name='mobilegameanalytica',
            name='odd_type',
            field=models.CharField(choices=[('promo4', 'Promo 4'), ('mohio', 'Mohio'), ('promo', 'Promo'), ('promo2', 'Promo 2'), ('promo3', 'Promo 3'), ('promo5', 'Promo 5'), ('promo6', 'Promo 6'), ('type1', 'Type 1'), ('type2', 'Type 2'), ('mohio2', 'Mohio 2')], default='promo4', max_length=20),
        ),
    ]
