# Generated by Django 5.0.6 on 2024-07-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keno', '0007_ticket_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='odd_type',
            new_name='keno_odd_type',
        ),
        migrations.RenameField(
            model_name='gameanalytica',
            old_name='odd_type',
            new_name='keno_odd_type',
        ),
        migrations.RenameField(
            model_name='mobilegame',
            old_name='odd_type',
            new_name='keno_odd_type',
        ),
        migrations.RenameField(
            model_name='mobilegameanalytica',
            old_name='odd_type',
            new_name='keno_odd_type',
        ),
    ]
